# Generated by Django 2.1.2 on 2019-02-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brandName',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
