# Generated by Django 2.1.2 on 2019-02-14 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_auto_20190214_0800'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brandName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brand.Brand'),
            preserve_default=False,
        ),
    ]
