# Generated by Django 2.1.2 on 2019-02-14 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_brandname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brandName',
            new_name='brand',
        ),
    ]
