# Generated by Django 2.1.2 on 2019-02-14 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_auto_20190214_0913'),
        ('product', '0004_remove_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brand.Brand'),
            preserve_default=False,
        ),
    ]
